POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
  "username": "dimych",
  "password": "12345"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###